export const DROPDOWN_ACTION_TYPES={
    ADD_ITEM_TO_CART:'dropdown/ADD_ITEM_TO_CART',
    CHANGE_CART_ITEM_QUANTITY:'dropdown/CHANGE_CART_ITEM_QUANTITY',
    CHANGE_CART_OPEN:'dropdown/CHANGE_CART_OPEN',
    SET_TOTAL:'dropdown/SET_TOTAL',
    SET_CART_COUNT:'dropdown/SET_CART_COUNT',
    SET_CART_ITEMS:'dropdown/SET_CART_ITEMS'
}